version: '3.8'

services:
  quantum-trading-system:
    build: .
    container_name: quantum-trading
    restart: unless-stopped
    environment:
      - POSTGRES_URL=postgresql://quantum:quantum_pass@postgres:5432/quantum_trading
      - REDIS_URL=redis://redis:6379
      - CLICKHOUSE_URL=clickhouse://clickhouse:8123/quantum_analytics
      - GRAFANA_URL=http://grafana:3000
      - ENV=production
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./config:/app/config
    networks:
      - quantum-network
    depends_on:
      - postgres
      - redis
      - clickhouse
      - grafana
    deploy:
      resources:
        limits:
          memory: 16G
          cpus: '8'
        reservations:
          memory: 8G
          cpus: '4'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:15-alpine
    container_name: quantum-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: quantum_trading
      POSTGRES_USER: quantum
      POSTGRES_PASSWORD: quantum_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - quantum-network
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: quantum-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 4gb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - quantum-network
    ports:
      - "6379:6379"

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: quantum-clickhouse
    restart: unless-stopped
    environment:
      CLICKHOUSE_DB: quantum_analytics
      CLICKHOUSE_USER: quantum
      CLICKHOUSE_PASSWORD: quantum_pass
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.xml
    networks:
      - quantum-network
    ports:
      - "8123:8123"
      - "9000:9000"

  grafana:
    image: grafana/grafana:latest
    container_name: quantum-grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_PASSWORD: quantum_admin
      GF_INSTALL_PLUGINS: grafana-clickhouse-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - quantum-network
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:latest
    container_name: quantum-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - quantum-network
    ports:
      - "9090:9090"

  nginx:
    image: nginx:alpine
    container_name: quantum-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - quantum-network
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - quantum-trading-system

  vault:
    image: vault:latest
    container_name: quantum-vault
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: quantum-root-token
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    volumes:
      - vault_data:/vault/data
    networks:
      - quantum-network
    ports:
      - "8200:8200"

  wireguard:
    image: linuxserver/wireguard:latest
    container_name: quantum-vpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PUID: 1000
      PGID: 1000
      TZ: UTC
      SERVERURL: auto
      SERVERPORT: 51820
      PEERS: 10
    volumes:
      - wireguard_data:/config
      - /lib/modules:/lib/modules
    networks:
      - quantum-network
    ports:
      - "51820:51820/udp"

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.0
    container_name: quantum-filebeat
    restart: unless-stopped
    user: root
    volumes:
      - ./logs:/app/logs:ro
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - quantum-network

networks:
  quantum-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
  redis_data:
  clickhouse_data:
  grafana_data:
  prometheus_data:
  vault_data:
  wireguard_data: