apiVersion: v1
kind: ConfigMap
metadata:
  name: quantum-config
  namespace: quantum-trading
data:
  POSTGRES_HOST: quantum-postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: quantum_trading
  REDIS_HOST: quantum-redis
  REDIS_PORT: "6379"
  CLICKHOUSE_HOST: quantum-clickhouse
  CLICKHOUSE_PORT: "8123"
  GRAFANA_HOST: quantum-grafana
  GRAFANA_PORT: "3000"
  ENVIRONMENT: production
  LOG_LEVEL: INFO
  MAX_WORKERS: "8"
  GPU_ENABLED: "true"

---